### ISSUE TITLE
Image Fallbacks

### ISSUE THREAD

**Issue by nzdev** [DigitalMomentum/MetaMomentum#1]
Hi, great work on this package! Does this support fallbacks in the preview for images?

Thanks

**Comment by dinc5150** [comment]
Thanks for the feedback @nzdev !

No, it doesn't support fallbacks as yet, but it's something that I'd like to add soon to the package. I got a bit swamped with other work, so just wanted to get the package out for now.

You could in the meantime, update the razor view to fall back to another property in the model. Obviously, this won't be reflected in the preview in the backoffice though.

**Comment by dinc5150** [comment]
@nzdev , I've pushed V1.1 to NuGet with the new feature to allow fallbacks to the image. It will work with the Media Picker and limited support for upload fields. 

You may need to update your view, changing `@Model.MetaMomentum.ShareImage` to `@Model.MetaMomentum.ShareImageUrl`. This was done to support the Upload picker.

thanks for your feedback, let me know if you have any issues with it.
