### ISSUE TITLE
Setting for the "noindex" toggle

### ISSUE THREAD

**Issue by torerikk** [DigitalMomentum/MetaMomentum#10]
Would it be possible to add a setting to disable the "noindex" toggle? I need more functionality than what a simple toggle gives me, and would like to not show the toggle to avoid confusing our editors. :)

**Comment by dinc5150** [comment]
Thanks @torerikk , I'll be adding an option to remove the button in the next release. 

I'll add the option to hide the option. 
When hidden it will default to always index, however you will be able to override the view with your custom logic.

**Comment by torerikk** [comment]
That's great, thanks!
