### ISSUE TITLE
Labels are broken in Momentum for Umbraco 10

### ISSUE THREAD

**Issue by martinlcp** [DigitalMomentum/MetaMomentum#12]
![momentum broken v10](https://user-images.githubusercontent.com/883638/198560156-78b8b083-9858-4e19-bc3c-d279a3ed6bf8.jpg)

The labels seem to be out of alignment and not how they were appearing in previous releases....

![Edit_SEO_Screenshot](https://user-images.githubusercontent.com/883638/198560252-a081d9d4-1eea-4369-ad58-c9c64d63e010.png)

**Comment by dinc5150** [comment]
Thanks @martinjgriffiths, I've just checked a couple of my V10 sites which are using the latest dev build and they look OK. The new build is using the latest UUI updates, and I was reluctant to release the update before testing them in my own sites as UUI is so new, but they are working much better than the screenshots above, so I'll try and get a release update out to you shortly.

In the meantime, if your able to update to 2.2.0-alpha and test it out, that would be great:
https://www.myget.org/feed/digital-momentum/package/nuget/MetaMomentum
https://www.myget.org/feed/digital-momentum/package/nuget/MetaMomentum.Core

Even though they have been marked as Alpha, I have them running on a couple of production sites, so should be pretty stable.

**Comment by martinlcp** [comment]
@dinc5150  Hey David

Tried Nuget'ing got following error....

NU1102: Unable to find package MetaMomentum with version (>= 2.2.0-beta)

**Comment by dinc5150** [comment]
Hi @martinjgriffiths ,

My only thought is that maybe you haven't configured to use the MyGet source or the wrong source is selected?

Try installing using the following commands which specifies the MyGet source:

`Install-Package MetaMomentum.Core -Version 2.2.0-beta -Source https://www.myget.org/F/digital-momentum/api/v3/index.json` 

`Install-Package MetaMomentum -Version 2.2.0-beta -Source https://www.myget.org/F/digital-momentum/api/v3/index.json`

**Comment by martinlcp** [comment]
@dinc5150 Many thanks, you're right I didn't notice it was a different repo. Once configured I could install the package. The improvements are lovely, I really like your social icon buttons, a great idea! The labels are aligned properly now too.

![image](https://user-images.githubusercontent.com/883638/199946890-c9e7a26a-8861-4995-991f-4ae5c6a6e342.png)

One very small note, imo there's a bit of a UI smell around widget width in Umbraco. Some default to roughly 3/4 of the usable screen container width. Some (nested content) take up the full width and a few are configurable (small, medium, large). Can I recommend you add the overlay size option?

![image](https://user-images.githubusercontent.com/883638/199946767-8aea9649-b6e6-4680-9ce1-d193c183f34d.png)

**Comment by dinc5150** [comment]
Thanks, I'll have to do some research into the sizing. It usually refers to the overlay in the popup window, but I'm not sure if there would be a standardised set of widths in the main window of the property editor. 
I'll chat to some other package devs to see how they have approached the problem.
