### ISSUE TITLE
Improve Umbraco UI/UX in Umbraco v9/10

### ISSUE THREAD

**Issue by martinlcp** [DigitalMomentum/MetaMomentum#13]
![image](https://user-images.githubusercontent.com/883638/198560847-d24ede95-8a5f-40a5-9d59-671d5c809e5b.png)
![image](https://user-images.githubusercontent.com/883638/198561125-f883996f-b740-4027-ab4c-7317edf71af7.png)
![image](https://user-images.githubusercontent.com/883638/198561180-abbf3900-b497-487e-9fe7-08d30709dd15.png)
![image](https://user-images.githubusercontent.com/883638/198561732-732ef8d7-6345-4006-a745-39cea72bf3c5.png)

Can the UI/UX be improved to bring in line with latest Umbraco UI controls?

**Comment by dinc5150** [comment]
Yes, Please see the alpha release which uses the new UUI library thats recently been released:
https://www.myget.org/feed/digital-momentum/package/nuget/MetaMomentum
https://www.myget.org/feed/digital-momentum/package/nuget/MetaMomentum.Core
