### ISSUE TITLE
Stable release for v9 stable?

### ISSUE THREAD

**Issue by AaronSadlerUK** [DigitalMomentum/MetaMomentum#4]
Will you be releasing a stable for the V9 stable?

**Comment by dinc5150** [comment]
Hi @AaronSadlerUK ,

Yes, I only have 1 V9 site in production so far, but its stable to use, with a couple of the below caveats.

There is an existing bug that affects fallbacks to the upload field which affects both V8/V9 but about to release a new version that fixes that.  

Your other issue has highlighted that I have missed pulling in the TwitterName and OGSiteName from the AppSettings file, so I'll quickly fix that before I deploy the final release. TwitterName and OGSiteName currently return null. This shouldn't cause any issues, other than the tags not displaying.

I'll have these fixed and released in about the next day.

**Comment by AaronSadlerUK** [comment]
Brill thanks for the headsup.

My site is not currently in production, so doesn't bother me yet :)

**Comment by dinc5150** [comment]
@AaronSadlerUK, I've just released the latest version and the master branch has been updated, so maybe pull down the latest version of master and see if that helps.

**Comment by AaronSadlerUK** [comment]
Ok great!

I'll take a look and report back 👍😊
