### ISSUE TITLE
Remove HTML tags from values coming from fallback properties

### ISSUE THREAD

**Issue by ZioTino** [DigitalMomentum/MetaMomentum#8]
I have a rich text editor value that I need to use also as fallback value for the meta description.
Would be cool if the HTML tags will be removed from all the fallback property values.
(only tags, not HTML entities, which are correct)
![image](https://user-images.githubusercontent.com/39855999/153026739-27ef2af6-a388-4a74-9140-1d5b3d2239b5.png)

**Comment by dinc5150** [comment]
Sorry for the slow reply @ZioTino, I had not seen you issue till now. 

I'd recommend adding  @Html.StripHtml() around the content for the description [See Examples](https://our.umbraco.com/forum/using-umbraco-and-getting-started/99671-htmlstriphtml-plus-umbraco-8)

this should do for your above example:
```
<meta name="description" content="@Html.StripHtml(Model.Description)">
```

I'll keep this issue open and will look at it for the next release

**Comment by dinc5150** [comment]
After playing with this, I can now see that it's a bit more complicated than stripping the HTML from the Razor view. For example, the editor previews show the styled html. 

I've pushed it to the next minor version as it might introduce some unexpected breaking changes.

**Comment by dinc5150** [comment]
This has been tested and due for release in 2.2.0
