### ISSUE TITLE
Toggling between previews marks the page as "dirty"

### ISSUE THREAD

**Issue by s-daemen** [DigitalMomentum/MetaMomentum#9]
Switching between the different social platform previews marks the editor as "dirty". This causes Umbraco to show a popup to stay or discard the changes when navigating away from the current page even though no changes to the content have been made.

**Comment by dinc5150** [comment]
Thanks @Link-SD, I hadn't noticed that. Very annoying once you do! 

I'll fix that for the next release.

**Comment by dinc5150** [comment]
This has been resolved in the V2/2.1.1 branch and will be included in the next release
